### PR TITLE
add filepath in top line.

### PR DESCRIPTION
**Pull request by xucongli1989**
1:nothing to selected.

> //D:\MyData\GitHub\CopyWithLineNumbers\CopyWithLineNumbers\CopyWithLineNumbersCommand.cs  (15)

2:select some code.

> //D:\MyData\GitHub\CopyWithLineNumbers\CopyWithLineNumbers\CopyWithLineNumbersCommand.cs  (75)
>    75:             OleMenuCommandService commandService = this.ServiceProvider.GetService(typeof(IMenuCommandService)) as OleMenuCommandService;
>    76:             if (commandService != null)
>    77:             {
>    78:                 var menuCommandID = new CommandID(CommandSet, CommandId);
>    79:                 var menuItem = new OleMenuCommand(this.MenuItemCallback, menuCommandID);
>    80:                 menuItem.BeforeQueryStatus += this.BeforeQueryStatus;
>    81:                 commandService.AddCommand(menuItem);
>    82:             }

### CODE REVIEW

**Comment by m-tmatma** [comment]
Your pull request is not acceptable as it is because your pull request will change the existing command.
If you want such feature, you need to implement as a new command without changing the existing command.

And you need to share codes between the existing command and the new command
by passing a flag which controls whether to add a filename or not.

And if you create a pull request, you should create a feature branch for it.

**Comment by m-tmatma** [comment]
Users may want to choose a format from several formats. So it may be better to add the customize command for format
instead of adding each command for each format.

**Comment by xucongli1989** [comment]
With filepath is my want.But I don't know how to add option window tab in vs settings.So it's ok nothing to merge my request to your code.Thanks a lot.

**Comment by m-tmatma** [comment]
I assume the following.

- Add a new customize command at Tool menu. 
- When the command is invoked, it will show up the customize dialog box and save the settings to the registory
- CopyWithLineNumbers command makes output based on the registory configuration.

I'll make an investigation, but it may require some time because I can take time only on weekends.

**Comment by xucongli1989** [comment]
OK,I'm not in a hurry.And I have no develop's experience with vs plugin.Thanks a lot.You can close it.

**Comment by m-tmatma** [comment]
created #3.

**Pull request closed without merging**
