### PR TITLE
Issue12 replace tab to space

### PR DESCRIPTION
**Pull request by m-tmatma**
Add a new Variable that tabs in the selection are replaced to spaces.

### CODE REVIEW

**Comment by m-tmatma** [comment]
Hi @xucongli1989

 I added a new Variable {SelectionNoTab} that tabs in the selection are replaced to spaces.
Could you give me your thought?

**Comment by xucongli1989** [comment]
That's OK.I found a bug a moment ago,it's not show menu in `css,cshtml` file.
2017-07-15 13_35_36-xclcms - microsoft visual studio
2017-07-15 13_36_01-xclcms - microsoft visual studio

**Comment by m-tmatma** [comment]
I created the issue at #14.

**Comment by m-tmatma** [comment]
Please use the feature by the item in Tool menu until #14 will be fixed.

**Pull request merged**
