### PR TITLE
the context menu doesn't appear for css or html

### PR DESCRIPTION
**Pull request by m-tmatma**
the context menu doesn't appear for css or html.

Add support for css, html, and json.

### CODE REVIEW

**Comment by m-tmatma** [comment]
Hi @xucongli1989

I fixed the bug that you had reported.
I added support for css, html, and json.

What kind of file types do you think it should support?

**Comment by xucongli1989** [comment]
OK,but you should follow `VS document` with opened ,no config by yourself.

**Comment by m-tmatma** [comment]
What do you mean 'follow VS document with opened'?
What I have changed is to add GUID entry for css, html, and json.
'IDM_VS_CTXT_CODEWIN' doesn't cover css, html, and json file.

**Comment by xucongli1989** [comment]
OK,it is enough.I mean you should use all of text files that `VS` can opened.I don't know the theory of `VS Plugin Develop`.My English is not good,sorry.You can close the bug if you support `html,css`.Thanks a lot.

**Comment by m-tmatma** [comment]
merged #15

**Pull request merged**
