### PR TITLE
implement the configuration dialog for the format

### PR DESCRIPTION
**Pull request by m-tmatma**
implemented the configuration dialog

copywithlinenumbersconfiguration

The some treaks are needed, but the main implementation is done.

### CODE REVIEW

**Comment by m-tmatma** [comment]
Hi @xucongli1989

I implemented your feature request by adding the configuration dialog.
Please check whether to satisfy your need.

**Comment by xucongli1989** [comment]
OK,I will try it off duty.On first sight,it's my want.And thank  you very much for take so much time on it.I hope this plugin will be popular.Thanks a lot again.

**Comment by xucongli1989** [comment]
I think it is a little complex.

2017-06-26 20_46_28-xclcms - microsoft visual studio

Mark 1:
Can it become a custom textbox? Like a template input.For example: {{fileName}},{{fileFullName}},{{lineNumber}},{{selectedCode}} are keywords,and they are fixed.

Like this:

> //{{fileFullName}}{{lineNumber}}\n{{selectedCode}}\n...

Mark 2:
It is line number of all selected code to custom?Can it be removed?

That's my suggestion,it's not important.And you should follow your mind.And it's OK enough for me.

At first,it's a good plugin with this little function.Thanks a lot.

**Comment by m-tmatma** [comment]
I'll consider it.

**Comment by m-tmatma** [comment]
I implemented your suggestion.
There is a issue that Visual studio 2015 and 2017 share the same registry key.
Visual Studio 2015 and 2017 may have different versions of this plugins.

copywithlinenumbersconfiguration2

**Comment by xucongli1989** [comment]
Thanks a lot.Waiting for issue to MS's market.You're awesome.

**Comment by m-tmatma** [comment]
Please let me know if you have more suggestions,
and review my code if possible.

**Comment by m-tmatma** [comment]
What do you think about changing "Set Default" button to the ComboBox which makes it possible to set the textbox text to a preset string.

**Comment by xucongli1989** [comment]
I try it just now.It has a little bug.

2017-07-01 20_51_22-copywithlinenumbers - microsoft visual studio
2017-07-01 20_52_06-untitled1 _ - editplus

I think the right is:
`78return dte.Windows.Item(EnvDTE.Constants.vsWindowKindOutput);78`

**Comment by m-tmatma** [comment]
Do you expect {Selection} has no line numbers?
This plugin's aim is to quote selected text with adding line numbers for each line.
{Selection} contains line numbers at the beginning of the lines and contains a line ending at the end.
So your result is an intended behavior.

**Comment by xucongli1989** [comment]
Sorry,I ignore line numbers of each code line.You're right.Can you modify `{LineNumber}` to `{TopLineNumber}`?

**Comment by m-tmatma** [comment]
I renamed {LineNumber} to {TopLineNumber}.

**Comment by xucongli1989** [comment]
I have a new discovery.
2017-07-01 21_20_17-copywithlinenumbers - microsoft visual studio
2017-07-01 21_20_40-untitled1 _ - editplus

1:The template textbox can't press `Enter`,and it become the `OK` button.
2:`Mark 1` should remove spaces,`Mark 2` should be short.

**Comment by xucongli1989** [comment]
It's OK for my use.You can issue it to plugin market.

**Comment by m-tmatma** [comment]
1. If you want to insert a line ending, press "Insert EOL" button.
2. If there is no space at mark 1 and the widths of line numbers differ between the beginning of the selection and the end of the selection, it is not easy to read. Image that you select from line 1 to line 100.
The beginning of the quoted text isdifferent.
At Mark 2, I added one space. Do you think it is better that there is no space at the place.

**Comment by m-tmatma** [comment]
If you press Enter key at the other setting at Options setting, you'll find that the dialog will be closed.
I think this behavior can't be changed. But I also think it is convenient to use Enter Key to insert an end of line.

**Comment by xucongli1989** [comment]
1:About `Mark 1`
OK,but you can count the max line number and to count the chars.It's not important.That's OK.

2:About `Mark 2`
Yes I think.

Note:You can changed nothing too,and issue it to plugin market,I'll install it at first time.Thanks for your plugin.

**Comment by m-tmatma** [comment]
You're right.

I found String.PadLeft 
I think the extra spaces can be removed.

**Comment by m-tmatma** [comment]
I removed the extra space at Mark 1.

If the original texts have some spaces at the beginning of the lines, it is easy to read to have no extra space after colon. But if the original texts have no space there, I think that it is better to insert a space after colon. What do you think?

**Comment by xucongli1989** [comment]
OK,keep `Mark 2` invariable,I'm no issue anymore.Thanks a lot.

**Comment by m-tmatma** [comment]
fixed a bug that calculation of bottomLine was wrong.
added {BottomLineNumber}

**Comment by m-tmatma** [comment]
merged #4

**Pull request merged**
